[book]
title = "Data Reliability Engineering"
authors = ["Jefferson Roth"]
language = "en"
multilingual = false
src = "src"

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output.html]
additional-js = ["assets/mermaid.min.js", "assets/mermaid-init.js"]