[book]
title = "Data Reliability Engineering"
authors = ["Jefferson Roth"]
language = "en"
multilingual = false
src = "src"

[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]
marker = "* auto-gen TOC;\n{:toc}"
max-level = 4

[preprocessor.mermaid]
command = "mdbook-mermaid"

[preprocessor.plantuml]
plantuml-cmd="plantuml.exe"

[preprocessor.admonish]
command = "mdbook-admonish"

[preprocessor.template]

[preprocessor.svgbob]

[output.html]
additional-js = ["assets/mermaid.min.js", "assets/mermaid-init.js"]
additional-css = ["assets/mdbook-admonish.css", "assets/catppuccin.css", "assets/catppuccin-highlight.css"]

[output.html.print]
enable = true

[output.pdf]