[book]
title = "Data Reliability Engineering"
authors = ["Jefferson Roth"]
language = "en"
multilingual = true
src = "src"

# Translations
[[output.i18n.translations]]
language = "es"
translators = ["Jefferson Roth"]
title = "Ingeniería y Confiabilidad de Datos"

# Preprocessors
# Table of Contents
[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]
marker = "* auto-gen TOC;\n{:toc}"
max-level = 4

# Footnote
[preprocessor.footnote]

# Mermaid
[preprocessor.mermaid]
command = "mdbook-mermaid"

# PlantUML
[preprocessor.plantuml]
plantuml-cmd="plantuml.exe"

# Admonish
# [preprocessor.admonish]
# command = "mdbook-admonish"

# Template
[preprocessor.template]

# SVG Bob
# [preprocessor.svgbob]

# Katex LaTex
# [preprocessor.katex]
# renderers = ["html"]

# Emoji Codes
[preprocessor.emojicodes]

# Outputs
# Linkcheck
[output.linkcheck]

# HTML
[output.html]
additional-js = ["assets/mermaid.min.js", "assets/mermaid-init.js"]
additional-css = ["assets/mdbook-admonish.css", "assets/catppuccin.css", "assets/catppuccin-highlight.css"]
# mathjax-support = true

[output.html.print]
enable = true

# PDF
[output.pdf]

# MAN
# [output.man]

# Katex LaTex
# [output.katex]

# EPUB
# [output.epub]