version: "3.7"
services:
  app:
    build: .
    environment:
      - USER=$USER
    ports:
      - "3001:3000"
    volumes:
      - .:/usr/src/app:cached # Mount current directory to a non-root directory in the container
      - /usr/src/app/target # Persist the cargo build cache
      - /usr/src/app/book # Persist the generated book if necessary
    working_dir: /usr/src/app # Set the working directory to where the volume is mounted
    networks:
      - my_custom_network

  dev:
    image: jeffroth/mdbook-environment-dev:latest
    volumes:
      - .:/usr/src/app:cached # Mount current directory to a non-root directory in the container
    working_dir: /usr/src/app # Set the working directory to where the volume is mounted
    networks:
      - my_custom_network

networks:
  my_custom_network:
    driver: bridge
