@startmindmap Systems Reliability
+_ Systems Reliability
++ Impediments
+++ Failures
+++ Errors
+++ Defects
++ Mechanisms
+++ Fault Prevention: Avoidance
+++ Fault Tolerance
++++ Full Tolerance
++++ Controlled Degradation
++++ Fail-Safe
+++ Fault Prevention: Elimination
+++ Fault Predictions
++ Reliability Toolkit
-- Attributes
--- Reliability
--- Availability
--- Dependability
--- Safety
--- Integrity
--- Maintainability
--- Scalability
--- Deficiencies
@endmindmap