@startmindmap Systems Reliability
+_ Systems Reliability
++ Impediments
+++ Failures
+++ Errors
+++ Defects
++ Mechanisms
+++ Fault Prevention: Avoidance
+++ Fault Tolerance
+++ Fault Prevention: Elimination
+++ Fault Predictions
+++ Reliability Tools
-- Attributes
--- Reliability
--- Availability
--- Dependability
--- Safety
--- Integrity
--- Maintainability
--- Scalability
--- Deficiencies
@endmindmap