name: Publish mdbook to GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:
    branches-ignore:
      - "hotfix/**"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Validate Markdown Files
        uses: DavidAnson/markdownlint-cli2-action@v15
        with:
          config: ".github/files/config.markdownlint-cli2.jsonc"

      - name: Validate Markdown URLs
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-quiet-mode: "no"
          use-verbose-mode: "yes"
          check-modified-files-only: "yes"
          folder-path: "src"
          file-path: "./README.md"
          config-file: ".github/files/markdown.links.config.json"

  build:
    runs-on: ubuntu-latest
    needs: validate
    container: jeffroth/mdbook-environment:latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Build with mdBook
        run: |
          mdbook build

      - name: List book directory contents
        run: ls -R ./book

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: book
          path: ./book

  deploy:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: Download book directory artifact
        uses: actions/download-artifact@v2
        with:
          name: book
          path: ./book

      - name: List output files
        run: ls -R ./book

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.PERSONAL_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./book
